### PR TITLE
Add basic docker support

### PR DESCRIPTION
**Pull request by manfre**
Weird and wonderful birds deserve a container.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Haha, I didn't even write the settings system yet! I'll take it though - but I may move the docker files into a subdir

**Comment by andrewgodwin** [comment]
FWIW, I have not committed to a license yet, so can you confirm you'll release this and future contributions under BSD 3-clause for now, and I may tighten it up later?

**Comment by manfre** [comment]
> FWIW, I have not committed to a license yet, so can you confirm you'll release this and future contributions under BSD 3-clause for now, and I may tighten it up later?

You are free to license this PR however you want. 

Feel free to move the docker files to a subdir. Polluting the root is so common I usually start there to avoid overthinking it. 🤷‍♂️

**Comment by andrewgodwin** [comment]
Ta!

**Pull request merged**
