### PR TITLE
Fix docker compose

### PR DESCRIPTION
**Pull request by humrochagf**
- Adds the missing env vars to docker compose for it to be runnable by someone trying it for the first time
- Fix the naming on the image and db to match with the good one of the project name

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I'm actually still rapidly iterating the docker stuff on my end, so I'll leave this until I'm done and then we can see what else is needed.

**Comment by humrochagf** [comment]
Sure, no problem, thanks for this great project btw :slightly_smiling_face: 
In my changes it still lacks something to serve the static files like a nginx or traefik bridge.

**Comment by andrewgodwin** [comment]
Yeah, I have whitenoise on the local version I'm playing around with to do that, with the idea that a CDN can be put in front if needed.

**Comment by shivan-s** [comment]
@humrochagf thanks for this :)

Also, would it be worth setting up a local docker environment? Wondering if I should create an issue.

**Comment by manfre** [comment]
@andrewgodwin Since you're still iterating on docker, I'll avoid a PR. I suggest only setting `--bind` in `start.sh` and leaving the rest to `$GUNICORN_CMD_ARGS`. I intentionally avoided adding a `gunicorn.conf.py` because that could trample some PaaS settings.

```
diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
index 00463bf..7a54b2f 100644
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -25,6 +25,7 @@ services:
       - "POSTGRES_DB=tahake"
       - "POSTGRES_USER=postgres"
       - "POSTGRES_PASSWORD=insecure_password"
+      - "GUNICORN_CMD_ARGS=--workers 8"
     networks:
       - external_network
       - internal_network
diff --git a/docker/start.sh b/docker/start.sh
index 1c01b6e..d7dd3fd 100644
--- a/docker/start.sh
+++ b/docker/start.sh
@@ -2,4 +2,4 @@

 python3 manage.py migrate

-exec gunicorn takahe.wsgi:application -w 8 -b 0.0.0.0:8000
+exec gunicorn takahe.wsgi:application -b 0.0.0.0:8000
```

**Comment by andrewgodwin** [comment]
That's a good idea - I'll make that change along with some others today!

**Comment by humrochagf** [comment]
Just rebased it and squashed the commits to keep it clean, now with whitenoise everything is running smooth :slightly_smiling_face:

**Review by andrewgodwin — APPROVED** [review]

**Comment by andrewgodwin** [comment]
Lovely, thank you!

**Pull request merged**
